In [17]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [18]:

np.random.seed(42)

pd.set_option("display.float_format", lambda x: f"{x:.3f}")

## Part 1 - Data cleanning & Preprocessing

In [19]:
dataset_a = pd.DataFrame({
    "student_id": [1, 2, 3, 4, 5, 6, 7, 8],
    "age": [20, 21, np.nan, 22, 23, 20, np.nan, 24],
    "study_hours": [10, 12, 8, np.nan, 15, 10, 9, 14],
    "score": [85, 90, 78, 88, np.nan, 82, 80, 91]
})

dataset_a.head()

   student_id    age  study_hours  score
0           1 20.000       10.000 85.000
1           2 21.000       12.000 90.000
2           3    NaN        8.000 78.000
3           4 22.000          NaN 88.000
4           5 23.000       15.000    NaN

In [20]:
print("Missing values per column:")
print(dataset_a.isnull().sum())

Missing values per column:
student_id     0
age            2
study_hours    1
score          1
dtype: int64

In [21]:
dataset_a_clean = dataset_a.copy()

for col in ["age", "study_hours", "score"]:
    mean_value = dataset_a_clean[col].mean()
    dataset_a_clean[col] = dataset_a_clean[col].fillna(mean_value)

dataset_a_clean

   student_id    age  study_hours  score
0           1 20.000       10.000 85.000
1           2 21.000       12.000 90.000
2           3 21.667        8.000 78.000
3           4 22.000       11.143 88.000
4           5 23.000       15.000 84.857
5           6 20.000       10.000 82.000
6           7 21.667        9.000 80.000
7           8 24.000       14.000 91.000

**Note** The mean is only one of several imputation strategies. Other common options are the **median** (more robust to outliers), the **mode** (useful for categorical columns), or more advanced techniques like KNN imputation. The right choice depends on the data.

In [ ]:
dataset_b = pd.DataFrame({
    "brand": ["Toyota", "toyota", "HONDA", "Ford","ford", "Toyota", "Honda", "TOYOTA"],
    "model": ["Corolla", "Corolla", "Civic", "Focus", "Focus", "Corolla", "Civic", "Corolla"],
    "price": ["15000", "15000", "18000", "12000", "15000", "18500", "15000"],
    "year": [2018, 2018, 2019, 2017, 2017, 2018, 2020, 2018],

})